{% set name = "findiff" %}
{% set version = "0.12.1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: f5bad8f52a5f21f55903c0c9fa2bd243fbbd78fe8143d3e0b5a41abf4dbae54c

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"
  noarch: python

requirements:
  host:
    - python >=3.6
    - pip >=21.0.1
    - pytest-runner >=5.3.0
  run:
    - numpy >=1.14.2
    - python >=3.6
    - scipy >=1.3.1
    - sympy >=1.8

test:
  commands:
    - pip check
  requires:
    - pip
  imports:
    - findiff

about:
  home: "https://github.com/maroba/findiff"
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: "A Python package for finite difference derivatives in any number of dimensions."

extra:
  recipe-maintainers:
    - tnigon
    - maroba
    - og113
